/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 25 20:55:18 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Voluntario_ESTest extends Voluntario_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Voluntario voluntario0 = new Voluntario();
      assertFalse(voluntario0.estaDisponivel());
      
      voluntario0.setDisponivel(true);
      boolean boolean0 = voluntario0.estaDisponivel();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Voluntario voluntario0 = new Voluntario();
      voluntario0.setRaio((-2215.3286615859683));
      Voluntario voluntario1 = voluntario0.clone();
      assertFalse(voluntario1.estaDisponivel());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Voluntario voluntario0 = new Voluntario();
      Voluntario voluntario1 = voluntario0.clone();
      assertFalse(voluntario1.estaDisponivel());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Voluntario voluntario0 = new Voluntario("", "1", "", (Ponto2D) null, 822.50960729417, 1091, 1091, true);
      Voluntario voluntario1 = voluntario0.clone();
      assertTrue(voluntario1.estaDisponivel());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Voluntario voluntario0 = null;
      try {
        voluntario0 = new Voluntario((Voluntario) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Perfil", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Voluntario voluntario0 = new Voluntario();
      Voluntario voluntario1 = new Voluntario(voluntario0);
      assertFalse(voluntario1.estaDisponivel());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Voluntario voluntario0 = new Voluntario();
      boolean boolean0 = voluntario0.estaDisponivel();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Ponto2D ponto2D0 = mock(Ponto2D.class, new ViolatedAssumptionAnswer());
      doReturn("^Xc").when(ponto2D0).toString();
      Voluntario voluntario0 = new Voluntario("^Xc", "^Xc", "^Xc", ponto2D0, 0.6037720658009351, (-1749), (-1749), false);
      Voluntario voluntario1 = voluntario0.clone();
      assertFalse(voluntario1.estaDisponivel());
  }
}
